# Generated by Django 4.0.6 on 2022-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0003_rename_billing_amount_contract_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='pay_out_day',
            field=models.DateField(null=True),
        ),
    ]
