# Generated by Django 4.0.6 on 2022-09-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0004_alter_saving_pay_out_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringsaving',
            old_name='billing_frequency',
            new_name='frequency',
        ),
    ]
