# Generated by Django 4.0.6 on 2022-09-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0005_rename_billing_frequency_recurringsaving_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='pay_out_day',
        ),
    ]
