# Generated by Django 4.0.6 on 2022-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0005_alter_contract_billing_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='billing_frequency',
            field=models.IntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (12, 'Annualy')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringsaving',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (12, 'Annualy')], default=1, max_length=10),
        ),
    ]
