# Generated by Django 4.0.6 on 2022-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0006_remove_saving_pay_out_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringsaving',
            name='pay_out_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='pay_out_day',
            field=models.DateField(null=True),
        ),
    ]
