# Generated by Django 4.0.6 on 2022-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0007_recurringsaving_pay_out_day_saving_pay_out_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringsaving',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saving',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
